server:
  port: 8002

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

spring:
  application:
    name: hearu
  servlet:
    multipart:
      #上传文件的最大值
      max-file-size: 15MB
      #请求文件的最大值
      max-request-size: 50MB


guardian:
  token:
    private-key: 'newxnbnewxyyds666'
