server:
  port: 8002

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

spring:
  application:
    name: hearu


guardian:
  token:
    private-key: 'newxnbnewxyyds666'