spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hearu?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: phpmyadmin
    password: newx

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

server:
  port: 8002